version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels: ["component/dependencies"]

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels: ["component/dependencies"]
    ignore:
      - # Needs to be updated along with NodeJS version.
        dependency-name: "@types/node"
        versions: [ ">20" ]
      - # Need to migrate to Vue 3 before moving beyond 2.7.x.
        dependency-name: "vue"
        versions: [ ">2" ]
      - # @vue/test-utils v2 is for Vue 3; we're on Vue 2 for now
        dependency-name: "@vue/test-utils"
        versions: [ ">1" ]
      - # Since we no longer pull in Nuxt (i.e. we have "ejected"), newer
        # versions of this package mis-detect and think we're using Nuxt 3 (with
        # Vue 3), and uses the wrong set of linters.  This happened in v12, so
        # we ignore everything higher than 11.
        dependency-name: "@nuxtjs/eslint-config-typescript"
        versions: [ ">11" ]
      - # Electron major bumps are too complicated; we need to do those manually.
        dependency-name: "electron"
        update-types: [ "version-update:semver-major" ]
      - # node-fetch 3+ requires ECMAScript modules, but Electron doesn't
        # support that. See https://github.com/electron/electron/issues/21457
        dependency-name: "node-fetch"
        versions: [ ">2" ]
      - # This needs to be done in lockstep with node-fetch.
        dependency-name: "@types/node-fetch"
        versions: [ ">2" ]
      - # We don't utilize @rancher/shell in a meaningful way. It is safe to
        # ignore until we arrive a solution that uses it.
        dependency-name: "@rancher/shell"
        versions: [ ">0.1" ]
      - # unfetch release 5.0.0 dropped necessary files.
        # See https://github.com/developit/unfetch/issues/ 162, 163, 167, 172, 176
        # Not the best-maintained library out there.
        # It's used only by the nuxt pseudo-submodule
        # Assume the next release will fix it.
        dependency-name: "unfetch"
        versions: [ "5.0.0" ]
      - # fs-xattr 0.4.0 later are esm-only.
        dependency-name: "fs-xattr"
        versions: [ ">0.3"]

  # Maintain dependencies for Golang
  - package-ecosystem: "gomod"
    directory: "/src/go/docker-credential-none"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    labels: ["component/dependencies"]
    reviewers: [ "jandubois" ]

  - package-ecosystem: "gomod"
    directory: "/src/go/extension-proxy"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    labels: ["component/dependencies"]
    reviewers: [ "Nino-K" ]

  - package-ecosystem: "gomod"
    directory: "/src/go/github-runner-monitor"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    labels: ["component/dependencies"]
    reviewers: [ "mook-as" ]

  - package-ecosystem: "gomod"
    directory: "/src/go/guestagent"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    labels: ["component/dependencies"]
    reviewers: [ "Nino-K" ]

  - package-ecosystem: "gomod"
    directory: "/src/go/mock-wsl"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    labels: ["component/dependencies"]
    reviewers: [ "Nino-K" ]

  - package-ecosystem: "gomod"
    directory: "/src/go/nerdctl-stub"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    labels: ["component/dependencies"]
    reviewers: [ "Nino-K" ]

  - package-ecosystem: "gomod"
    directory: "/src/go/nerdctl-stub/generate"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    labels: ["component/dependencies"]
    reviewers: [ "Nino-K" ]

  - package-ecosystem: "gomod"
    directory: "/src/go/networking"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    labels: ["component/dependencies"]
    reviewers: [ "Nino-K" ]

  - package-ecosystem: "gomod"
    directory: "/src/go/rdctl"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    labels: ["component/dependencies"]
    reviewers: [ "jandubois" ]

  - package-ecosystem: "gomod"
    directory: "/src/go/wsl-helper"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    labels: ["component/dependencies"]
    reviewers: [ "Nino-K" ]

  - package-ecosystem: docker
    directory: /bats/tests/compose/testdata/app
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /bats/tests/compose/testdata/app
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /bats/tests/extensions/testdata
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /pkg/rancher-desktop/sudo-prompt
    schedule:
      interval: daily
