# This workflow builds the GitHub runner
name: 'GitHub Runner: Build Monitor'

on:
  push:
    paths: [ src/go/github-runner-monitor/** ]
  pull_request:
    paths: [ src/go/github-runner-monitor/** ]
  workflow_dispatch:

permissions:
  # This uses external actions, lock things down to read-only.
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        persist-credentials: false
        sparse-checkout: |
          src/go/github-runner-monitor
          .github/workflows/config
    - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version-file: go.work
        cache-dependency-path: src/go/github-runner-monitor/go.sum
    - run: go build .
      working-directory: src/go/github-runner-monitor
      env:
        CGO_ENABLED: '0'
        GOWORK: off
    - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: github-runner-linux
        path: src/go/github-runner-monitor/github-runner-monitor
        if-no-files-found: error
    - uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
      # This is only safe because this workflow does not allow writing
      with:
        args: --config=${{ github.workspace }}/.github/workflows/config/.golangci.yaml  --verbose --timeout 3m
        working-directory: src/go/github-runner-monitor
        only-new-issues: true
      env:
        GOWORK: off
