# This workflow builds the Linux self-hosted GitHub Runner disk image.
name: 'GitHub Runner: Build Linux Image'

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/opensuse/leap:15
      options: --privileged
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - run: >-
        zypper --non-interactive install python3-kiwi kiwi-systemdeps-disk-images sudo tar
    - run: echo 'ALL ALL=(ALL:ALL) NOPASSWD:ALL' > /etc/sudoers.d/nopasswd
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        persist-credentials: false
        sparse-checkout: src/disk-images/github-runner-linux
    - run: ./build-image.sh
      working-directory: src/disk-images/github-runner-linux
    - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: github-runner-image.qcow2.zip
        path: src/disk-images/github-runner-linux/*.qcow2
        if-no-files-found: error
