name: e2e tests on Linux

on:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'dependabot/**'
  pull_request: {}

jobs:
  check-paths:
    uses: ./.github/workflows/paths-ignore.yaml
  e2e-tests:
    needs: check-paths
    if: needs.check-paths.outputs.should-run == 'true'
    timeout-minutes: 150
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/yarn-install
      - name: Disable admin-access before start up
        run: |
          mkdir -p $HOME/.config/rancher-desktop
          cat <<EOF > $HOME/.config/rancher-desktop/settings.json
            {
              "version": 5,
              "application": {
                "adminAccess": false
              }
            }
          EOF
      - name: Enable kvm access
        run: sudo chmod a+rwx /dev/kvm
      - name: Run e2e Tests
        continue-on-error: false
        run: >-
          xvfb-run --auto-servernum --server-args='-screen 0 1280x960x24'
          yarn test:e2e
        env:
          RD_DEBUG_ENABLED: '1'
          CI: true
        timeout-minutes: 150
      - name: Upload failure reports
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        if: always()
        with:
          name: failure-reports.zip
          path: ./e2e/reports/*
      - name: Clean up test environment
        run: |
          rm -f $HOME/.config/rancher-desktop.defaults.json
          rm -f $HOME/.config/rancher-desktop.locked.json
        if: always()
