name: Test

on:
  push: {}
  pull_request: {}

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        persist-credentials: false
    - uses: ./.github/actions/yarn-install
    - run: yarn build
    - run: yarn lint:nofix
    - name: Install shfmt
      run: go install mvdan.cc/sh/v3/cmd/shfmt@latest
    - run: make -C bats lint
    - run: yarn test
  lint:
    strategy:
      matrix:
        # We run the Linux lint in the `test` flow, no need to repeat it.
        runs-on: [windows-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - if: runner.os == 'Windows'
      name: Configure git to use Unix line endings
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        persist-credentials: false
    - uses: ./.github/actions/yarn-install
    - run: yarn lint:nofix
