name: Generate Upgrade Test Data
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        include:
        - platform: mac
          arch: x86_64
          runs-on: macos-13
        - platform: mac
          arch: aarch64
          runs-on: macos-latest
        - platform: win
          runs-on: windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        persist-credentials: false
        # Needed to run `git describe` to get full version info
        fetch-depth: 0
    - uses: ./.github/actions/yarn-install
    - run: yarn build
    - run: yarn package
    - name: Upload Windows installer
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: Rancher Desktop Setup.msi
        path: dist/Rancher.Desktop*.msi
        if-no-files-found: error
    - if: runner.os == 'Windows'
      run: cat dist/electron-builder.yaml
    - name: Upload Windows build information
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: build-info.yml
        path: dist/electron-builder.yaml
        if-no-files-found: error
    - name: Upload macOS archive
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      if: matrix.platform == 'mac'
      with:
        name: Rancher Desktop-mac.${{ matrix.arch }}.zip
        path: dist/Rancher Desktop*.zip
        if-no-files-found: error
  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        persist-credentials: false
    - uses: ./.github/actions/yarn-install
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        ref: gh-pages
        path: pages
        persist-credentials: true
    - name: Download installer (msi)
      id: msi
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: Rancher Desktop Setup.msi
        path: RD_SETUP_MSI
    - name: Download mac x86_64 archive
      id: mac_x86_64
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: Rancher Desktop-mac.x86_64.zip
        path: MACX86_ZIP
    - name: Download mac aarch64 archive
      id: mac_aarch64
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: Rancher Desktop-mac.aarch64.zip
        path: MACARM_ZIP
    - name: Download build information
      id: info
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: build-info.yml
        path: RD_BUILD_INFO
    - run: node scripts/ts-wrapper.js scripts/populate-update-server.ts
      env:
        RD_SETUP_MSI: ${{ steps.msi.outputs.download-path }}
        RD_MACX86_ZIP: ${{ steps.mac_x86_64.outputs.download-path }}
        RD_MACARM_ZIP: ${{ steps.mac_aarch64.outputs.download-path }}
        RD_BUILD_INFO: ${{ steps.info.outputs.download-path }}
        RD_OUTPUT_DIR: ${{ github.workspace }}/pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
