name: e2e tests on Windows

on:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'dependabot/**'
  pull_request: {}

defaults:
  run:
    shell: powershell
jobs:
  check-paths:
    uses: ./.github/workflows/paths-ignore.yaml
  e2e-tests:
    needs: check-paths
    if: needs.check-paths.outputs.should-run == 'true'
    timeout-minutes: 90
    runs-on: windows-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-environment
      - uses: ./.github/actions/yarn-install
      - name: Run e2e Tests
        run: yarn test:e2e
        env:
          RD_DEBUG_ENABLED: '1'
      - name: Upload failure reports
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        if: always()
        with:
          name: e2etest-artifacts
          path: ./e2e/reports/*
